##### Numerical Python - numpy - basis of many computational packages

In [ ]:
# Better to import numpy as np instead of * as np has libraries with similar names as standard
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc("figure", figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

Numpy features -

- ndArray - n dimensional array operations without using for loop
- Read/write arrays to disk/memorymapped files
- Linerr algebra, random numbers, fourier transformation
- C api for connecting NumPy with libraries written in C/C++/Fortran
- While good for numerical analysis, for statistical analysys better use Panda
- Numpy internally stores data in a contiguous block of memory, its internal C libraries can operate on this w/0 type checing


In [1]:
# Performance difference of np array and python list. Create a 1M numbers first.
import numpy as np

my_arr = np.arange(1_000_000)          # arange is similar to range function in standard
my_list = list(range(1_000_000))

In [12]:
# To multiply each element by 2 - numpy is 100s of times faster

%timeit my_arr2 = my_arr * 2
%timeit my_list2 = [x * 2 for x in my_list]

807 µs ± 37.1 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
25.9 ms ± 1.66 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [11]:
type (my_arr)

numpy.ndarray

In [15]:
# Simple array 
import numpy as np
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [16]:
# Multiply each element by 10
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [17]:
# Or double each element
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [18]:
data.shape  # How many elements in each dimension and how many dimensions

(2, 3)

In [19]:
data.dtype  # data types of the elements

dtype('float64')

###### Creating an array

In [21]:
data1 = [6, 7.5, 8, 0, 1]                   # Create from a list
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [20]:
data = np.array(range(1,21,4))              # or sequence numbers
data

array([ 1,  5,  9, 13, 17])

In [22]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]         # list of lists - 2 dimensional array
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
arr2.ndim                   # Number of dimensions

2

In [24]:
arr2.shape

(2, 4)

In [25]:
arr1.dtype
arr2.dtype

dtype('int64')

In [26]:
# np.zeros creates array of all zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
np.zeros((3, 6))   # Two dimensions

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [38]:
np.ones ((2, 3, 4))  # Three dimensions 

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [49]:
# np.empty returns un-initialized memory, usually zero but possible to have "garbage" values

np.empty((2,2))

array([[6. , 7.5],
       [8. , 1. ]])

In [57]:
# Change the size of the empty array and you may get other values Try 4 first and then 10 below
np.empty (10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
np.arange(15)  # creating an array using range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [58]:
arr1 = np.array([1, 2, 3], dtype=np.float64)  # possible to override Python inferred data types
arr1.dtype

dtype('float64')

In [59]:
# data types - float, int (signed and unsigned), boolean, complex, object, string

arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2.dtype

dtype('int32')

In [60]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype
float_arr = arr.astype(np.float64)        # convert the datatype for the 2nd array
float_arr
float_arr.dtype

dtype('float64')

In [61]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr
arr.astype(np.int32)        # converting to int "floors" the numbers

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [16]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)
numeric_strings.astype(float)

# Be careful with numpy string data type - string is fixed length and may truncate data w/o warning

In [62]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)   # short form to have int_array same as calibers

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [63]:
zeros_uint32 = np.zeros(8, dtype="u4") # u4 is sane as int32
zeros_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

##### Arithmatic operations using numpy 

In [69]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [65]:
arr * arr   # Square every number

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [70]:
arr +=  arr  # Double every number
arr

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [71]:
1 / arr  

array([[0.5       , 0.25      , 0.16666667],
       [0.125     , 0.1       , 0.08333333]])

In [73]:
arr ** 0.5 # Square root

array([[1.41421356, 2.        , 2.44948974],
       [2.82842712, 3.16227766, 3.46410162]])

In [74]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2
arr2 > arr   # Creates a boolean array

array([[False, False, False],
       [False, False, False]])

##### Basic index and slixe

In [75]:
arr = np.arange(10)   # One dimensional similar to lists
arr
arr[5]

5

In [78]:
arr[5:10:2]         # Basic slicing

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [80]:
arr[-1:0:-1]      # simple reverse

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [81]:
arr[5:8] = 12     # make these values identical
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [82]:
arr_slice = arr[5:8]    # slice of an array is a view of the original array arr
arr_slice

array([12, 12, 12])

In [83]:
arr_slice[1] = 12345   # Changing slice changes the original array also
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [84]:
arr_slice[:] = 64      # Slice with just a colon - means all the elements of the slice
arr

# Note instead of a view if you want to copy an array you have to use the copy function arr[5:8].copy()

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [91]:
# For 2 dimensional array each element is an one dimensional array or similar to list

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2d[2]

In [87]:
arr2d[0][2]      # To get the 0th row, 2nd column

3

In [88]:
arr2d[0,2]        # alternate way - 0th row, 2nd column

3

In [89]:
# 3 dimensional array

arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [92]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
arr3d[0,1,2]

6

In [94]:
old_values = arr3d[0].copy()
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [96]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [97]:
arr3d[1, 0]

array([7, 8, 9])

In [98]:
x = arr3d[1]
x
x[0]

array([7, 8, 9])

In [99]:
arr
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [100]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [103]:
lower_dim_slice = arr2d[1, :2]
lower_dim_slice

array([4, 5])

In [104]:
lower_dim_slice.shape

(2,)

In [105]:
arr2d[:2, 2]

array([3, 6])

In [106]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [40]:
arr2d[:2, 1:] = 0
arr2d

###### Boolean indexing - an array of names and another array - similar shape - of numbers

In [107]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [108]:
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],
                 [-12, -4], [3, 4]])
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [109]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [112]:
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

In [111]:
data[names == "Bob", 1:]

array([[7],
       [0]])

In [113]:
data[names == "Bob", 1]

array([7, 0])

In [114]:
names != "Bob"  # Also not equals to 
~(names == "Bob")
data[~(names == "Bob")]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [46]:
cond = names == "Bob"
data[~cond]

In [47]:
mask = (names == "Bob") | (names == "Will")
mask
data[mask]

In [48]:
data[data < 0] = 0
data

In [49]:
data[names != "Joe"] = 7
data

In [50]:
arr = np.zeros((8, 4))
for i in range(8):
    arr[i] = i
arr

In [51]:
arr[[4, 3, 0, 6]]

In [52]:
arr[[-3, -5, -7]]

In [53]:
arr = np.arange(32).reshape((8, 4))
arr
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

In [54]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

In [55]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]
arr[[1, 5, 7, 2], [0, 3, 1, 2]] = 0
arr

In [56]:
arr = np.arange(15).reshape((3, 5))
arr
arr.T

In [57]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
arr
np.dot(arr.T, arr)

In [58]:
arr.T @ arr

In [59]:
arr
arr.swapaxes(0, 1)

In [60]:
samples = np.random.standard_normal(size=(4, 4))
samples

In [61]:
from random import normalvariate
N = 1_000_000
%timeit samples = [normalvariate(0, 1) for _ in range(N)]
%timeit np.random.standard_normal(N)

In [62]:
rng = np.random.default_rng(seed=12345)
data = rng.standard_normal((2, 3))

In [63]:
type(rng)

In [64]:
arr = np.arange(10)
arr
np.sqrt(arr)
np.exp(arr)

In [65]:
x = rng.standard_normal(8)
y = rng.standard_normal(8)
x
y
np.maximum(x, y)

In [66]:
arr = rng.standard_normal(7) * 5
arr
remainder, whole_part = np.modf(arr)
remainder
whole_part

In [67]:
arr
out = np.zeros_like(arr)
np.add(arr, 1)
np.add(arr, 1, out=out)
out

In [68]:
points = np.arange(-5, 5, 0.01) # 100 equally spaced points
xs, ys = np.meshgrid(points, points)
ys

In [69]:
z = np.sqrt(xs ** 2 + ys ** 2)
z

In [70]:
import matplotlib.pyplot as plt
plt.imshow(z, cmap=plt.cm.gray, extent=[-5, 5, -5, 5])
plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

In [71]:
plt.draw()

In [72]:
plt.close("all")

In [73]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [74]:
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result

In [75]:
result = np.where(cond, xarr, yarr)
result

In [76]:
arr = rng.standard_normal((4, 4))
arr
arr > 0
np.where(arr > 0, 2, -2)

In [77]:
np.where(arr > 0, 2, arr) # set only positive values to 2

In [78]:
arr = rng.standard_normal((5, 4))
arr
arr.mean()
np.mean(arr)
arr.sum()

In [79]:
arr.mean(axis=1)
arr.sum(axis=0)

In [80]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

In [81]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

In [82]:
arr.cumsum(axis=0)
arr.cumsum(axis=1)

In [83]:
arr = rng.standard_normal(100)
(arr > 0).sum() # Number of positive values
(arr <= 0).sum() # Number of non-positive values

In [84]:
bools = np.array([False, False, True, False])
bools.any()
bools.all()

In [85]:
arr = rng.standard_normal(6)
arr
arr.sort()
arr

In [86]:
arr = rng.standard_normal((5, 3))
arr

In [87]:
arr.sort(axis=0)
arr
arr.sort(axis=1)
arr

In [88]:
arr2 = np.array([5, -10, 7, 1, 0, -3])
sorted_arr2 = np.sort(arr2)
sorted_arr2

In [89]:
names = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])
np.unique(names)
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

In [90]:
sorted(set(names))

In [91]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

In [92]:
arr = np.arange(10)
np.save("some_array", arr)

In [93]:
np.load("some_array.npy")

In [94]:
np.savez("array_archive.npz", a=arr, b=arr)

In [95]:
arch = np.load("array_archive.npz")
arch["b"]

In [96]:
np.savez_compressed("arrays_compressed.npz", a=arr, b=arr)

In [97]:
!rm some_array.npy
!rm array_archive.npz
!rm arrays_compressed.npz

In [98]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x
y
x.dot(y)

In [99]:
np.dot(x, y)

In [100]:
x @ np.ones(3)

In [101]:
from numpy.linalg import inv, qr
X = rng.standard_normal((5, 5))
mat = X.T @ X
inv(mat)
mat @ inv(mat)

In [102]:
import random
position = 0
walk = [position]
nsteps = 1000
for _ in range(nsteps):
    step = 1 if random.randint(0, 1) else -1
    position += step
    walk.append(position)


In [103]:
plt.figure()

In [104]:
plt.plot(walk[:100])

In [105]:
nsteps = 1000
rng = np.random.default_rng(seed=12345)  # fresh random generator
draws = rng.integers(0, 2, size=nsteps)
steps = np.where(draws == 0, 1, -1)
walk = steps.cumsum()

In [106]:
walk.min()
walk.max()

In [107]:
(np.abs(walk) >= 10).argmax()

In [108]:
nwalks = 5000
nsteps = 1000
draws = rng.integers(0, 2, size=(nwalks, nsteps)) # 0 or 1
steps = np.where(draws > 0, 1, -1)
walks = steps.cumsum(axis=1)
walks

In [109]:
walks.max()
walks.min()

In [110]:
hits30 = (np.abs(walks) >= 30).any(axis=1)
hits30
hits30.sum() # Number that hit 30 or -30

In [111]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(axis=1)
crossing_times

In [112]:
crossing_times.mean()

In [113]:
draws = 0.25 * rng.standard_normal((nwalks, nsteps))